/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package br.com.maidahealth.telemedapi.avro;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class MessageReadRequest extends org.apache.avro.specific.SpecificRecordBase {
  private static final long serialVersionUID = 1099500163234651124L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"MessageReadRequest\",\"fields\":[{\"name\":\"api_key\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"avro.java.string\":\"String\"},{\"name\":\"chat_id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"avro.java.string\":\"String\"},{\"name\":\"participant_uuid\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"avro.java.string\":\"String\"},{\"name\":\"offset\",\"type\":\"int\",\"avro.java.int\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<MessageReadRequest> ENCODER =
      new BinaryMessageEncoder<MessageReadRequest>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<MessageReadRequest> DECODER =
      new BinaryMessageDecoder<MessageReadRequest>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<MessageReadRequest> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<MessageReadRequest> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<MessageReadRequest> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<MessageReadRequest>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this MessageReadRequest to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a MessageReadRequest from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a MessageReadRequest instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static MessageReadRequest fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String api_key;
  private java.lang.String chat_id;
  private java.lang.String participant_uuid;
  private int offset;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public MessageReadRequest() {}

  /**
   * All-args constructor.
   * @param api_key The new value for api_key
   * @param chat_id The new value for chat_id
   * @param participant_uuid The new value for participant_uuid
   * @param offset The new value for offset
   */
  public MessageReadRequest(java.lang.String api_key, java.lang.String chat_id, java.lang.String participant_uuid, java.lang.Integer offset) {
    this.api_key = api_key;
    this.chat_id = chat_id;
    this.participant_uuid = participant_uuid;
    this.offset = offset;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return api_key;
    case 1: return chat_id;
    case 2: return participant_uuid;
    case 3: return offset;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: api_key = value$ != null ? value$.toString() : null; break;
    case 1: chat_id = value$ != null ? value$.toString() : null; break;
    case 2: participant_uuid = value$ != null ? value$.toString() : null; break;
    case 3: offset = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'api_key' field.
   * @return The value of the 'api_key' field.
   */
  public java.lang.String getApiKey() {
    return api_key;
  }


  /**
   * Sets the value of the 'api_key' field.
   * @param value the value to set.
   */
  public void setApiKey(java.lang.String value) {
    this.api_key = value;
  }

  /**
   * Gets the value of the 'chat_id' field.
   * @return The value of the 'chat_id' field.
   */
  public java.lang.String getChatId() {
    return chat_id;
  }


  /**
   * Sets the value of the 'chat_id' field.
   * @param value the value to set.
   */
  public void setChatId(java.lang.String value) {
    this.chat_id = value;
  }

  /**
   * Gets the value of the 'participant_uuid' field.
   * @return The value of the 'participant_uuid' field.
   */
  public java.lang.String getParticipantUuid() {
    return participant_uuid;
  }


  /**
   * Sets the value of the 'participant_uuid' field.
   * @param value the value to set.
   */
  public void setParticipantUuid(java.lang.String value) {
    this.participant_uuid = value;
  }

  /**
   * Gets the value of the 'offset' field.
   * @return The value of the 'offset' field.
   */
  public int getOffset() {
    return offset;
  }


  /**
   * Sets the value of the 'offset' field.
   * @param value the value to set.
   */
  public void setOffset(int value) {
    this.offset = value;
  }

  /**
   * Creates a new MessageReadRequest RecordBuilder.
   * @return A new MessageReadRequest RecordBuilder
   */
  public static br.com.maidahealth.telemedapi.avro.MessageReadRequest.Builder newBuilder() {
    return new br.com.maidahealth.telemedapi.avro.MessageReadRequest.Builder();
  }

  /**
   * Creates a new MessageReadRequest RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new MessageReadRequest RecordBuilder
   */
  public static br.com.maidahealth.telemedapi.avro.MessageReadRequest.Builder newBuilder(br.com.maidahealth.telemedapi.avro.MessageReadRequest.Builder other) {
    if (other == null) {
      return new br.com.maidahealth.telemedapi.avro.MessageReadRequest.Builder();
    } else {
      return new br.com.maidahealth.telemedapi.avro.MessageReadRequest.Builder(other);
    }
  }

  /**
   * Creates a new MessageReadRequest RecordBuilder by copying an existing MessageReadRequest instance.
   * @param other The existing instance to copy.
   * @return A new MessageReadRequest RecordBuilder
   */
  public static br.com.maidahealth.telemedapi.avro.MessageReadRequest.Builder newBuilder(br.com.maidahealth.telemedapi.avro.MessageReadRequest other) {
    if (other == null) {
      return new br.com.maidahealth.telemedapi.avro.MessageReadRequest.Builder();
    } else {
      return new br.com.maidahealth.telemedapi.avro.MessageReadRequest.Builder(other);
    }
  }

  /**
   * RecordBuilder for MessageReadRequest instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<MessageReadRequest>{

    private java.lang.String api_key;
    private java.lang.String chat_id;
    private java.lang.String participant_uuid;
    private int offset;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(br.com.maidahealth.telemedapi.avro.MessageReadRequest.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.api_key)) {
        this.api_key = data().deepCopy(fields()[0].schema(), other.api_key);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.chat_id)) {
        this.chat_id = data().deepCopy(fields()[1].schema(), other.chat_id);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.participant_uuid)) {
        this.participant_uuid = data().deepCopy(fields()[2].schema(), other.participant_uuid);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.offset)) {
        this.offset = data().deepCopy(fields()[3].schema(), other.offset);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing MessageReadRequest instance
     * @param other The existing instance to copy.
     */
    private Builder(br.com.maidahealth.telemedapi.avro.MessageReadRequest other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.api_key)) {
        this.api_key = data().deepCopy(fields()[0].schema(), other.api_key);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.chat_id)) {
        this.chat_id = data().deepCopy(fields()[1].schema(), other.chat_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.participant_uuid)) {
        this.participant_uuid = data().deepCopy(fields()[2].schema(), other.participant_uuid);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.offset)) {
        this.offset = data().deepCopy(fields()[3].schema(), other.offset);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'api_key' field.
      * @return The value.
      */
    public java.lang.String getApiKey() {
      return api_key;
    }


    /**
      * Sets the value of the 'api_key' field.
      * @param value The value of 'api_key'.
      * @return This builder.
      */
    public br.com.maidahealth.telemedapi.avro.MessageReadRequest.Builder setApiKey(java.lang.String value) {
      validate(fields()[0], value);
      this.api_key = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'api_key' field has been set.
      * @return True if the 'api_key' field has been set, false otherwise.
      */
    public boolean hasApiKey() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'api_key' field.
      * @return This builder.
      */
    public br.com.maidahealth.telemedapi.avro.MessageReadRequest.Builder clearApiKey() {
      api_key = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'chat_id' field.
      * @return The value.
      */
    public java.lang.String getChatId() {
      return chat_id;
    }


    /**
      * Sets the value of the 'chat_id' field.
      * @param value The value of 'chat_id'.
      * @return This builder.
      */
    public br.com.maidahealth.telemedapi.avro.MessageReadRequest.Builder setChatId(java.lang.String value) {
      validate(fields()[1], value);
      this.chat_id = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'chat_id' field has been set.
      * @return True if the 'chat_id' field has been set, false otherwise.
      */
    public boolean hasChatId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'chat_id' field.
      * @return This builder.
      */
    public br.com.maidahealth.telemedapi.avro.MessageReadRequest.Builder clearChatId() {
      chat_id = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'participant_uuid' field.
      * @return The value.
      */
    public java.lang.String getParticipantUuid() {
      return participant_uuid;
    }


    /**
      * Sets the value of the 'participant_uuid' field.
      * @param value The value of 'participant_uuid'.
      * @return This builder.
      */
    public br.com.maidahealth.telemedapi.avro.MessageReadRequest.Builder setParticipantUuid(java.lang.String value) {
      validate(fields()[2], value);
      this.participant_uuid = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'participant_uuid' field has been set.
      * @return True if the 'participant_uuid' field has been set, false otherwise.
      */
    public boolean hasParticipantUuid() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'participant_uuid' field.
      * @return This builder.
      */
    public br.com.maidahealth.telemedapi.avro.MessageReadRequest.Builder clearParticipantUuid() {
      participant_uuid = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'offset' field.
      * @return The value.
      */
    public int getOffset() {
      return offset;
    }


    /**
      * Sets the value of the 'offset' field.
      * @param value The value of 'offset'.
      * @return This builder.
      */
    public br.com.maidahealth.telemedapi.avro.MessageReadRequest.Builder setOffset(int value) {
      validate(fields()[3], value);
      this.offset = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'offset' field has been set.
      * @return True if the 'offset' field has been set, false otherwise.
      */
    public boolean hasOffset() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'offset' field.
      * @return This builder.
      */
    public br.com.maidahealth.telemedapi.avro.MessageReadRequest.Builder clearOffset() {
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    public MessageReadRequest build() {
      try {
        MessageReadRequest record = new MessageReadRequest();
        record.api_key = fieldSetFlags()[0] ? this.api_key : (java.lang.String) defaultValue(fields()[0]);
        record.chat_id = fieldSetFlags()[1] ? this.chat_id : (java.lang.String) defaultValue(fields()[1]);
        record.participant_uuid = fieldSetFlags()[2] ? this.participant_uuid : (java.lang.String) defaultValue(fields()[2]);
        record.offset = fieldSetFlags()[3] ? this.offset : (java.lang.Integer) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<MessageReadRequest>
    WRITER$ = (org.apache.avro.io.DatumWriter<MessageReadRequest>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<MessageReadRequest>
    READER$ = (org.apache.avro.io.DatumReader<MessageReadRequest>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.api_key);

    out.writeString(this.chat_id);

    out.writeString(this.participant_uuid);

    out.writeInt(this.offset);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.api_key = in.readString();

      this.chat_id = in.readString();

      this.participant_uuid = in.readString();

      this.offset = in.readInt();

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.api_key = in.readString();
          break;

        case 1:
          this.chat_id = in.readString();
          break;

        case 2:
          this.participant_uuid = in.readString();
          break;

        case 3:
          this.offset = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










