/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package br.com.maidahealth.telemedapi.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class NewConversationRequest extends org.apache.avro.specific.SpecificRecordBase {
  private static final long serialVersionUID = -6024554102218418301L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"NewConversationRequest\",\"fields\":[{\"name\":\"api_key\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"avro.java.string\":\"String\"},{\"name\":\"participant_uuids\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"avro.java.string\":\"String\"}},{\"name\":\"generic_id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"avro.java.string\":\"String\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<NewConversationRequest> ENCODER =
      new BinaryMessageEncoder<NewConversationRequest>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<NewConversationRequest> DECODER =
      new BinaryMessageDecoder<NewConversationRequest>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<NewConversationRequest> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<NewConversationRequest> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<NewConversationRequest> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<NewConversationRequest>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this NewConversationRequest to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a NewConversationRequest from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a NewConversationRequest instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static NewConversationRequest fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String api_key;
  private java.util.List<java.lang.String> participant_uuids;
  private java.lang.String generic_id;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public NewConversationRequest() {}

  /**
   * All-args constructor.
   * @param api_key The new value for api_key
   * @param participant_uuids The new value for participant_uuids
   * @param generic_id The new value for generic_id
   */
  public NewConversationRequest(java.lang.String api_key, java.util.List<java.lang.String> participant_uuids, java.lang.String generic_id) {
    this.api_key = api_key;
    this.participant_uuids = participant_uuids;
    this.generic_id = generic_id;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return api_key;
    case 1: return participant_uuids;
    case 2: return generic_id;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: api_key = value$ != null ? value$.toString() : null; break;
    case 1: participant_uuids = (java.util.List<java.lang.String>)value$; break;
    case 2: generic_id = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'api_key' field.
   * @return The value of the 'api_key' field.
   */
  public java.lang.String getApiKey() {
    return api_key;
  }


  /**
   * Sets the value of the 'api_key' field.
   * @param value the value to set.
   */
  public void setApiKey(java.lang.String value) {
    this.api_key = value;
  }

  /**
   * Gets the value of the 'participant_uuids' field.
   * @return The value of the 'participant_uuids' field.
   */
  public java.util.List<java.lang.String> getParticipantUuids() {
    return participant_uuids;
  }


  /**
   * Sets the value of the 'participant_uuids' field.
   * @param value the value to set.
   */
  public void setParticipantUuids(java.util.List<java.lang.String> value) {
    this.participant_uuids = value;
  }

  /**
   * Gets the value of the 'generic_id' field.
   * @return The value of the 'generic_id' field.
   */
  public java.lang.String getGenericId() {
    return generic_id;
  }


  /**
   * Sets the value of the 'generic_id' field.
   * @param value the value to set.
   */
  public void setGenericId(java.lang.String value) {
    this.generic_id = value;
  }

  /**
   * Creates a new NewConversationRequest RecordBuilder.
   * @return A new NewConversationRequest RecordBuilder
   */
  public static br.com.maidahealth.telemedapi.avro.NewConversationRequest.Builder newBuilder() {
    return new br.com.maidahealth.telemedapi.avro.NewConversationRequest.Builder();
  }

  /**
   * Creates a new NewConversationRequest RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new NewConversationRequest RecordBuilder
   */
  public static br.com.maidahealth.telemedapi.avro.NewConversationRequest.Builder newBuilder(br.com.maidahealth.telemedapi.avro.NewConversationRequest.Builder other) {
    if (other == null) {
      return new br.com.maidahealth.telemedapi.avro.NewConversationRequest.Builder();
    } else {
      return new br.com.maidahealth.telemedapi.avro.NewConversationRequest.Builder(other);
    }
  }

  /**
   * Creates a new NewConversationRequest RecordBuilder by copying an existing NewConversationRequest instance.
   * @param other The existing instance to copy.
   * @return A new NewConversationRequest RecordBuilder
   */
  public static br.com.maidahealth.telemedapi.avro.NewConversationRequest.Builder newBuilder(br.com.maidahealth.telemedapi.avro.NewConversationRequest other) {
    if (other == null) {
      return new br.com.maidahealth.telemedapi.avro.NewConversationRequest.Builder();
    } else {
      return new br.com.maidahealth.telemedapi.avro.NewConversationRequest.Builder(other);
    }
  }

  /**
   * RecordBuilder for NewConversationRequest instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<NewConversationRequest>{

    private java.lang.String api_key;
    private java.util.List<java.lang.String> participant_uuids;
    private java.lang.String generic_id;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(br.com.maidahealth.telemedapi.avro.NewConversationRequest.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.api_key)) {
        this.api_key = data().deepCopy(fields()[0].schema(), other.api_key);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.participant_uuids)) {
        this.participant_uuids = data().deepCopy(fields()[1].schema(), other.participant_uuids);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.generic_id)) {
        this.generic_id = data().deepCopy(fields()[2].schema(), other.generic_id);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing NewConversationRequest instance
     * @param other The existing instance to copy.
     */
    private Builder(br.com.maidahealth.telemedapi.avro.NewConversationRequest other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.api_key)) {
        this.api_key = data().deepCopy(fields()[0].schema(), other.api_key);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.participant_uuids)) {
        this.participant_uuids = data().deepCopy(fields()[1].schema(), other.participant_uuids);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.generic_id)) {
        this.generic_id = data().deepCopy(fields()[2].schema(), other.generic_id);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'api_key' field.
      * @return The value.
      */
    public java.lang.String getApiKey() {
      return api_key;
    }


    /**
      * Sets the value of the 'api_key' field.
      * @param value The value of 'api_key'.
      * @return This builder.
      */
    public br.com.maidahealth.telemedapi.avro.NewConversationRequest.Builder setApiKey(java.lang.String value) {
      validate(fields()[0], value);
      this.api_key = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'api_key' field has been set.
      * @return True if the 'api_key' field has been set, false otherwise.
      */
    public boolean hasApiKey() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'api_key' field.
      * @return This builder.
      */
    public br.com.maidahealth.telemedapi.avro.NewConversationRequest.Builder clearApiKey() {
      api_key = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'participant_uuids' field.
      * @return The value.
      */
    public java.util.List<java.lang.String> getParticipantUuids() {
      return participant_uuids;
    }


    /**
      * Sets the value of the 'participant_uuids' field.
      * @param value The value of 'participant_uuids'.
      * @return This builder.
      */
    public br.com.maidahealth.telemedapi.avro.NewConversationRequest.Builder setParticipantUuids(java.util.List<java.lang.String> value) {
      validate(fields()[1], value);
      this.participant_uuids = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'participant_uuids' field has been set.
      * @return True if the 'participant_uuids' field has been set, false otherwise.
      */
    public boolean hasParticipantUuids() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'participant_uuids' field.
      * @return This builder.
      */
    public br.com.maidahealth.telemedapi.avro.NewConversationRequest.Builder clearParticipantUuids() {
      participant_uuids = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'generic_id' field.
      * @return The value.
      */
    public java.lang.String getGenericId() {
      return generic_id;
    }


    /**
      * Sets the value of the 'generic_id' field.
      * @param value The value of 'generic_id'.
      * @return This builder.
      */
    public br.com.maidahealth.telemedapi.avro.NewConversationRequest.Builder setGenericId(java.lang.String value) {
      validate(fields()[2], value);
      this.generic_id = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'generic_id' field has been set.
      * @return True if the 'generic_id' field has been set, false otherwise.
      */
    public boolean hasGenericId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'generic_id' field.
      * @return This builder.
      */
    public br.com.maidahealth.telemedapi.avro.NewConversationRequest.Builder clearGenericId() {
      generic_id = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public NewConversationRequest build() {
      try {
        NewConversationRequest record = new NewConversationRequest();
        record.api_key = fieldSetFlags()[0] ? this.api_key : (java.lang.String) defaultValue(fields()[0]);
        record.participant_uuids = fieldSetFlags()[1] ? this.participant_uuids : (java.util.List<java.lang.String>) defaultValue(fields()[1]);
        record.generic_id = fieldSetFlags()[2] ? this.generic_id : (java.lang.String) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<NewConversationRequest>
    WRITER$ = (org.apache.avro.io.DatumWriter<NewConversationRequest>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<NewConversationRequest>
    READER$ = (org.apache.avro.io.DatumReader<NewConversationRequest>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.api_key);

    long size0 = this.participant_uuids.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (java.lang.String e0: this.participant_uuids) {
      actualSize0++;
      out.startItem();
      out.writeString(e0);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

    out.writeString(this.generic_id);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.api_key = in.readString();

      long size0 = in.readArrayStart();
      java.util.List<java.lang.String> a0 = this.participant_uuids;
      if (a0 == null) {
        a0 = new SpecificData.Array<java.lang.String>((int)size0, SCHEMA$.getField("participant_uuids").schema());
        this.participant_uuids = a0;
      } else a0.clear();
      SpecificData.Array<java.lang.String> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.String>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          java.lang.String e0 = (ga0 != null ? ga0.peek() : null);
          e0 = in.readString();
          a0.add(e0);
        }
      }

      this.generic_id = in.readString();

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.api_key = in.readString();
          break;

        case 1:
          long size0 = in.readArrayStart();
          java.util.List<java.lang.String> a0 = this.participant_uuids;
          if (a0 == null) {
            a0 = new SpecificData.Array<java.lang.String>((int)size0, SCHEMA$.getField("participant_uuids").schema());
            this.participant_uuids = a0;
          } else a0.clear();
          SpecificData.Array<java.lang.String> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.String>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              java.lang.String e0 = (ga0 != null ? ga0.peek() : null);
              e0 = in.readString();
              a0.add(e0);
            }
          }
          break;

        case 2:
          this.generic_id = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










