/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package br.com.maidahealth.telemedapi.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class NewMessageRequest extends org.apache.avro.specific.SpecificRecordBase{
  private static final long serialVersionUID = 8565569063449049723L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"NewMessageRequest\",\"fields\":[{\"name\":\"api_key\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"avro.java.string\":\"String\"},{\"name\":\"chat_id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"avro.java.string\":\"String\"},{\"name\":\"sender_uuid\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"avro.java.string\":\"String\"},{\"name\":\"type\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"avro.java.string\":\"String\"},{\"name\":\"text_or_attachment_name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"avro.java.string\":\"String\"},{\"name\":\"attachment_base64\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"avro.java.string\":\"String\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<NewMessageRequest> ENCODER =
      new BinaryMessageEncoder<NewMessageRequest>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<NewMessageRequest> DECODER =
      new BinaryMessageDecoder<NewMessageRequest>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<NewMessageRequest> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<NewMessageRequest> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<NewMessageRequest> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<NewMessageRequest>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this NewMessageRequest to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a NewMessageRequest from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a NewMessageRequest instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static NewMessageRequest fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String api_key;
  private java.lang.String chat_id;
  private java.lang.String sender_uuid;
  private java.lang.String type;
  private java.lang.String text_or_attachment_name;
  private java.lang.String attachment_base64;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public NewMessageRequest() {}

  /**
   * All-args constructor.
   * @param api_key The new value for api_key
   * @param chat_id The new value for chat_id
   * @param sender_uuid The new value for sender_uuid
   * @param type The new value for type
   * @param text_or_attachment_name The new value for text_or_attachment_name
   * @param attachment_base64 The new value for attachment_base64
   */
  public NewMessageRequest(java.lang.String api_key, java.lang.String chat_id, java.lang.String sender_uuid, java.lang.String type, java.lang.String text_or_attachment_name, java.lang.String attachment_base64) {
    this.api_key = api_key;
    this.chat_id = chat_id;
    this.sender_uuid = sender_uuid;
    this.type = type;
    this.text_or_attachment_name = text_or_attachment_name;
    this.attachment_base64 = attachment_base64;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return api_key;
    case 1: return chat_id;
    case 2: return sender_uuid;
    case 3: return type;
    case 4: return text_or_attachment_name;
    case 5: return attachment_base64;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: api_key = value$ != null ? value$.toString() : null; break;
    case 1: chat_id = value$ != null ? value$.toString() : null; break;
    case 2: sender_uuid = value$ != null ? value$.toString() : null; break;
    case 3: type = value$ != null ? value$.toString() : null; break;
    case 4: text_or_attachment_name = value$ != null ? value$.toString() : null; break;
    case 5: attachment_base64 = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'api_key' field.
   * @return The value of the 'api_key' field.
   */
  public java.lang.String getApiKey() {
    return api_key;
  }


  /**
   * Sets the value of the 'api_key' field.
   * @param value the value to set.
   */
  public void setApiKey(java.lang.String value) {
    this.api_key = value;
  }

  /**
   * Gets the value of the 'chat_id' field.
   * @return The value of the 'chat_id' field.
   */
  public java.lang.String getChatId() {
    return chat_id;
  }


  /**
   * Sets the value of the 'chat_id' field.
   * @param value the value to set.
   */
  public void setChatId(java.lang.String value) {
    this.chat_id = value;
  }

  /**
   * Gets the value of the 'sender_uuid' field.
   * @return The value of the 'sender_uuid' field.
   */
  public java.lang.String getSenderUuid() {
    return sender_uuid;
  }


  /**
   * Sets the value of the 'sender_uuid' field.
   * @param value the value to set.
   */
  public void setSenderUuid(java.lang.String value) {
    this.sender_uuid = value;
  }

  /**
   * Gets the value of the 'type' field.
   * @return The value of the 'type' field.
   */
  public java.lang.String getType() {
    return type;
  }


  /**
   * Sets the value of the 'type' field.
   * @param value the value to set.
   */
  public void setType(java.lang.String value) {
    this.type = value;
  }

  /**
   * Gets the value of the 'text_or_attachment_name' field.
   * @return The value of the 'text_or_attachment_name' field.
   */
  public java.lang.String getTextOrAttachmentName() {
    return text_or_attachment_name;
  }


  /**
   * Sets the value of the 'text_or_attachment_name' field.
   * @param value the value to set.
   */
  public void setTextOrAttachmentName(java.lang.String value) {
    this.text_or_attachment_name = value;
  }

  /**
   * Gets the value of the 'attachment_base64' field.
   * @return The value of the 'attachment_base64' field.
   */
  public java.lang.String getAttachmentBase64() {
    return attachment_base64;
  }


  /**
   * Sets the value of the 'attachment_base64' field.
   * @param value the value to set.
   */
  public void setAttachmentBase64(java.lang.String value) {
    this.attachment_base64 = value;
  }

  /**
   * Creates a new NewMessageRequest RecordBuilder.
   * @return A new NewMessageRequest RecordBuilder
   */
  public static br.com.maidahealth.telemedapi.avro.NewMessageRequest.Builder newBuilder() {
    return new br.com.maidahealth.telemedapi.avro.NewMessageRequest.Builder();
  }

  /**
   * Creates a new NewMessageRequest RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new NewMessageRequest RecordBuilder
   */
  public static br.com.maidahealth.telemedapi.avro.NewMessageRequest.Builder newBuilder(br.com.maidahealth.telemedapi.avro.NewMessageRequest.Builder other) {
    if (other == null) {
      return new br.com.maidahealth.telemedapi.avro.NewMessageRequest.Builder();
    } else {
      return new br.com.maidahealth.telemedapi.avro.NewMessageRequest.Builder(other);
    }
  }

  /**
   * Creates a new NewMessageRequest RecordBuilder by copying an existing NewMessageRequest instance.
   * @param other The existing instance to copy.
   * @return A new NewMessageRequest RecordBuilder
   */
  public static br.com.maidahealth.telemedapi.avro.NewMessageRequest.Builder newBuilder(br.com.maidahealth.telemedapi.avro.NewMessageRequest other) {
    if (other == null) {
      return new br.com.maidahealth.telemedapi.avro.NewMessageRequest.Builder();
    } else {
      return new br.com.maidahealth.telemedapi.avro.NewMessageRequest.Builder(other);
    }
  }

  /**
   * RecordBuilder for NewMessageRequest instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<NewMessageRequest>{

    private java.lang.String api_key;
    private java.lang.String chat_id;
    private java.lang.String sender_uuid;
    private java.lang.String type;
    private java.lang.String text_or_attachment_name;
    private java.lang.String attachment_base64;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(br.com.maidahealth.telemedapi.avro.NewMessageRequest.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.api_key)) {
        this.api_key = data().deepCopy(fields()[0].schema(), other.api_key);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.chat_id)) {
        this.chat_id = data().deepCopy(fields()[1].schema(), other.chat_id);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.sender_uuid)) {
        this.sender_uuid = data().deepCopy(fields()[2].schema(), other.sender_uuid);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.type)) {
        this.type = data().deepCopy(fields()[3].schema(), other.type);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.text_or_attachment_name)) {
        this.text_or_attachment_name = data().deepCopy(fields()[4].schema(), other.text_or_attachment_name);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.attachment_base64)) {
        this.attachment_base64 = data().deepCopy(fields()[5].schema(), other.attachment_base64);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
    }

    /**
     * Creates a Builder by copying an existing NewMessageRequest instance
     * @param other The existing instance to copy.
     */
    private Builder(br.com.maidahealth.telemedapi.avro.NewMessageRequest other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.api_key)) {
        this.api_key = data().deepCopy(fields()[0].schema(), other.api_key);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.chat_id)) {
        this.chat_id = data().deepCopy(fields()[1].schema(), other.chat_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.sender_uuid)) {
        this.sender_uuid = data().deepCopy(fields()[2].schema(), other.sender_uuid);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.type)) {
        this.type = data().deepCopy(fields()[3].schema(), other.type);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.text_or_attachment_name)) {
        this.text_or_attachment_name = data().deepCopy(fields()[4].schema(), other.text_or_attachment_name);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.attachment_base64)) {
        this.attachment_base64 = data().deepCopy(fields()[5].schema(), other.attachment_base64);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'api_key' field.
      * @return The value.
      */
    public java.lang.String getApiKey() {
      return api_key;
    }


    /**
      * Sets the value of the 'api_key' field.
      * @param value The value of 'api_key'.
      * @return This builder.
      */
    public br.com.maidahealth.telemedapi.avro.NewMessageRequest.Builder setApiKey(java.lang.String value) {
      validate(fields()[0], value);
      this.api_key = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'api_key' field has been set.
      * @return True if the 'api_key' field has been set, false otherwise.
      */
    public boolean hasApiKey() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'api_key' field.
      * @return This builder.
      */
    public br.com.maidahealth.telemedapi.avro.NewMessageRequest.Builder clearApiKey() {
      api_key = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'chat_id' field.
      * @return The value.
      */
    public java.lang.String getChatId() {
      return chat_id;
    }


    /**
      * Sets the value of the 'chat_id' field.
      * @param value The value of 'chat_id'.
      * @return This builder.
      */
    public br.com.maidahealth.telemedapi.avro.NewMessageRequest.Builder setChatId(java.lang.String value) {
      validate(fields()[1], value);
      this.chat_id = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'chat_id' field has been set.
      * @return True if the 'chat_id' field has been set, false otherwise.
      */
    public boolean hasChatId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'chat_id' field.
      * @return This builder.
      */
    public br.com.maidahealth.telemedapi.avro.NewMessageRequest.Builder clearChatId() {
      chat_id = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'sender_uuid' field.
      * @return The value.
      */
    public java.lang.String getSenderUuid() {
      return sender_uuid;
    }


    /**
      * Sets the value of the 'sender_uuid' field.
      * @param value The value of 'sender_uuid'.
      * @return This builder.
      */
    public br.com.maidahealth.telemedapi.avro.NewMessageRequest.Builder setSenderUuid(java.lang.String value) {
      validate(fields()[2], value);
      this.sender_uuid = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'sender_uuid' field has been set.
      * @return True if the 'sender_uuid' field has been set, false otherwise.
      */
    public boolean hasSenderUuid() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'sender_uuid' field.
      * @return This builder.
      */
    public br.com.maidahealth.telemedapi.avro.NewMessageRequest.Builder clearSenderUuid() {
      sender_uuid = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'type' field.
      * @return The value.
      */
    public java.lang.String getType() {
      return type;
    }


    /**
      * Sets the value of the 'type' field.
      * @param value The value of 'type'.
      * @return This builder.
      */
    public br.com.maidahealth.telemedapi.avro.NewMessageRequest.Builder setType(java.lang.String value) {
      validate(fields()[3], value);
      this.type = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'type' field has been set.
      * @return True if the 'type' field has been set, false otherwise.
      */
    public boolean hasType() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'type' field.
      * @return This builder.
      */
    public br.com.maidahealth.telemedapi.avro.NewMessageRequest.Builder clearType() {
      type = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'text_or_attachment_name' field.
      * @return The value.
      */
    public java.lang.String getTextOrAttachmentName() {
      return text_or_attachment_name;
    }


    /**
      * Sets the value of the 'text_or_attachment_name' field.
      * @param value The value of 'text_or_attachment_name'.
      * @return This builder.
      */
    public br.com.maidahealth.telemedapi.avro.NewMessageRequest.Builder setTextOrAttachmentName(java.lang.String value) {
      validate(fields()[4], value);
      this.text_or_attachment_name = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'text_or_attachment_name' field has been set.
      * @return True if the 'text_or_attachment_name' field has been set, false otherwise.
      */
    public boolean hasTextOrAttachmentName() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'text_or_attachment_name' field.
      * @return This builder.
      */
    public br.com.maidahealth.telemedapi.avro.NewMessageRequest.Builder clearTextOrAttachmentName() {
      text_or_attachment_name = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'attachment_base64' field.
      * @return The value.
      */
    public java.lang.String getAttachmentBase64() {
      return attachment_base64;
    }


    /**
      * Sets the value of the 'attachment_base64' field.
      * @param value The value of 'attachment_base64'.
      * @return This builder.
      */
    public br.com.maidahealth.telemedapi.avro.NewMessageRequest.Builder setAttachmentBase64(java.lang.String value) {
      validate(fields()[5], value);
      this.attachment_base64 = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'attachment_base64' field has been set.
      * @return True if the 'attachment_base64' field has been set, false otherwise.
      */
    public boolean hasAttachmentBase64() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'attachment_base64' field.
      * @return This builder.
      */
    public br.com.maidahealth.telemedapi.avro.NewMessageRequest.Builder clearAttachmentBase64() {
      attachment_base64 = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    public NewMessageRequest build() {
      try {
        NewMessageRequest record = new NewMessageRequest();
        record.api_key = fieldSetFlags()[0] ? this.api_key : (java.lang.String) defaultValue(fields()[0]);
        record.chat_id = fieldSetFlags()[1] ? this.chat_id : (java.lang.String) defaultValue(fields()[1]);
        record.sender_uuid = fieldSetFlags()[2] ? this.sender_uuid : (java.lang.String) defaultValue(fields()[2]);
        record.type = fieldSetFlags()[3] ? this.type : (java.lang.String) defaultValue(fields()[3]);
        record.text_or_attachment_name = fieldSetFlags()[4] ? this.text_or_attachment_name : (java.lang.String) defaultValue(fields()[4]);
        record.attachment_base64 = fieldSetFlags()[5] ? this.attachment_base64 : (java.lang.String) defaultValue(fields()[5]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<NewMessageRequest>
    WRITER$ = (org.apache.avro.io.DatumWriter<NewMessageRequest>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<NewMessageRequest>
    READER$ = (org.apache.avro.io.DatumReader<NewMessageRequest>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.api_key);

    out.writeString(this.chat_id);

    out.writeString(this.sender_uuid);

    out.writeString(this.type);

    out.writeString(this.text_or_attachment_name);

    out.writeString(this.attachment_base64);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.api_key = in.readString();

      this.chat_id = in.readString();

      this.sender_uuid = in.readString();

      this.type = in.readString();

      this.text_or_attachment_name = in.readString();

      this.attachment_base64 = in.readString();

    } else {
      for (int i = 0; i < 6; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.api_key = in.readString();
          break;

        case 1:
          this.chat_id = in.readString();
          break;

        case 2:
          this.sender_uuid = in.readString();
          break;

        case 3:
          this.type = in.readString();
          break;

        case 4:
          this.text_or_attachment_name = in.readString();
          break;

        case 5:
          this.attachment_base64 = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










