package br.com.maidahealth.telemedapi.enums;

public enum TypeActionEnum {
	
	ATTENDANCE_IN_PROGRESS,
	INELIGIBLE_INSURED,
	INSURED_IN_QUEUE,
	WAITING_INSURED,
	CLOSED_TIME,
	NEXT_ONE,
	TOMORROW_ATTENDANCE,
	ATTENDANCE_ALMOST_CANCELLED,
	NEW_SCHEDULED_ATTENDANCE,
	PAYMENT_APPROVED
	;

}
