export * from './remote-my-payments/get-obligations-list';
export * from './remote-my-payments/get-boleto-pdf';
export * from './remote-my-payments/get-obligation-history';
export * from './remote-my-payments/get-history-years';
export * from './remote-my-payments/get-income-tax-years';
export * from './remote-my-payments/get-income-tax-details';
export * from './remote-my-payments/get-income-tax-pdf';
export * from './remote-my-payments/get-coparticipation';
export * from './remote-my-payments/get-coparticipation-pdf';
